# Generated by Django 5.1 on 2024-08-19 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_monthlyrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinghistory',
            name='parking_lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking.parkinglot'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MonthlyRevenue',
        ),
    ]
