# Generated by Django 5.1 on 2024-08-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parkinghistory_parking_lot_delete_monthlyrevenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='occupancy_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
