# Generated by Django 5.1 on 2024-08-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_parkinghistory_occupancy_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='occupancy_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
